In [2]:
import pandas as pd

westermo_df = pd.read_csv('westermo/flows/westermo.csv')

In [4]:
# Convert timestamps to Unix timestamp
westermo_df['startDate'] = pd.to_datetime(westermo_df['startDate']).astype('int64') / 10**9
westermo_df['endDate'] = pd.to_datetime(westermo_df['endDate']).astype('int64') / 10**9

In [5]:
westermo_df['IT_M_Label'].value_counts()

IT_M_Label
Normal                     23852
BAD-SSH                    22150
BAD-MITM                    6422
BAD-PORTSCAN2               5571
BAD-MISCONF-DUPLICATION     4611
BAD-MISCONF                 3889
BAD-PORTSCAN1               1566
GOOD-SSH                     668
Name: count, dtype: int64

In [6]:
westermo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68729 entries, 0 to 68728
Data columns (total 64 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   sAddress         68729 non-null  object 
 1   rAddress         68729 non-null  object 
 2   sMACs            68729 non-null  object 
 3   rMACs            68729 non-null  object 
 4   sIPs             57887 non-null  object 
 5   rIPs             57887 non-null  object 
 6   protocol         68729 non-null  object 
 7   startDate        68729 non-null  float64
 8   endDate          68729 non-null  float64
 9   start            68729 non-null  float64
 10  end              68729 non-null  float64
 11  startOffset      68729 non-null  float64
 12  endOffset        68729 non-null  float64
 13  duration         68729 non-null  float64
 14  sPackets         68729 non-null  int64  
 15  rPackets         68729 non-null  int64  
 16  sBytesSum        68729 non-null  int64  
 17  rBytesSum   

In [7]:
westermo_df.head()

sAddress       rAddress              sMACs              rMACs  \
0  198.18.134.11  198.18.134.12  b8:27:eb:6d:4f:4b  b8:27:eb:5b:50:19   
1  198.18.134.12  198.18.134.31  b8:27:eb:5b:50:19  b8:27:eb:3e:5d:96   
2  198.18.134.11  198.18.134.31  b8:27:eb:6d:4f:4b  b8:27:eb:3e:5d:96   
3  198.18.134.11  198.18.134.15  b8:27:eb:6d:4f:4b  b8:27:eb:15:88:9c   
4  198.18.134.12  198.18.134.15  b8:27:eb:5b:50:19  b8:27:eb:15:88:9c   

            sIPs           rIPs  protocol     startDate       endDate  \
0  198.18.134.11  198.18.134.12  IPV4-TCP  1.678444e+09  1.678444e+09   
1  198.18.134.12  198.18.134.31  IPV4-TCP  1.678444e+09  1.678444e+09   
2  198.18.134.11  198.18.134.31  IPV4-TCP  1.678444e+09  1.678444e+09   
3  198.18.134.11  198.18.134.15  IPV4-TCP  1.678444e+09  1.678444e+09   
4  198.18.134.12  198.18.134.15  IPV4-TCP  1.678444e+09  1.678444e+09   

          start  ...  sAckDelayMax  rAckDelayMax  sAckDelayMin  rAckDelayMin  \
0  1.678441e+09  ...         0.198         0.200           0.0           0.0   
1  1.678441e+09  ...         0.195         0.001           0.0           0.0   
2  1.678441e+09  ...         0.190         0.001           0.0           0.0   
3  1.678441e+09  ...         0.001         0.491           0.0           0.0   
4  1.678441e+09  ...         0.000         0.496           0.0           0.0   

   sAckDelayAvg  rAckDelayAvg  IT_B_Label  IT_M_Label  NST_B_Label  \
0      0.020279      0.028912           0      Normal            0   
1      0.020338      0.000455           0      Normal            0   
2      0.015988      0.000537           0      Normal            0   
3      0.000578      0.048820           0      Normal            0   
4      0.000423      0.077478           0      Normal            0   

   NST_M_Label  
0       Normal  
1       Normal  
2       Normal  
3       Normal  
4       Normal  

[5 rows x 64 columns]

In [8]:
westermo_df.describe()

startDate       endDate         start           end   startOffset  \
count  6.872900e+04  6.872900e+04  6.872900e+04  6.872900e+04  68729.000000   
mean   1.678447e+09  1.678447e+09  1.678443e+09  1.678443e+09   2747.186999   
std    1.574062e+03  1.574066e+03  1.574062e+03  1.574066e+03   1574.062202   
min    1.678444e+09  1.678444e+09  1.678441e+09  1.678441e+09      0.000000   
25%    1.678446e+09  1.678446e+09  1.678442e+09  1.678442e+09   1394.870249   
50%    1.678447e+09  1.678447e+09  1.678443e+09  1.678443e+09   2743.821532   
75%    1.678448e+09  1.678448e+09  1.678445e+09  1.678445e+09   4125.209604   
max    1.678450e+09  1.678450e+09  1.678446e+09  1.678446e+09   5443.588241   

          endOffset      duration      sPackets      rPackets     sBytesSum  \
count  68729.000000  68729.000000  68729.000000  68729.000000  68729.000000   
mean    2747.501637      0.314639     38.466106     29.529762   2673.185686   
std     1574.065929      0.211489     41.413802     27.212631   2953.707989   
min        0.000002      0.000001      0.000000      0.000000      0.000000   
25%     1394.955187      0.005006      4.000000      8.000000    380.000000   
50%     2744.232317      0.419887     16.000000     30.000000   1040.000000   
75%     4125.518950      0.473531     92.000000     48.000000   6560.000000   
max     5443.588243      0.500000    132.000000    774.000000  31384.000000   

       ...  sFragmentRate  rFragmentRate  sAckDelayMax  rAckDelayMax  \
count  ...        56523.0        52172.0  49844.000000  50804.000000   
mean   ...            0.0            0.0      0.111871      0.174028   
std    ...            0.0            0.0      0.096143      0.207029   
min    ...            0.0            0.0      0.000000      0.000000   
25%    ...            0.0            0.0      0.001000      0.001000   
50%    ...            0.0            0.0      0.189000      0.040000   
75%    ...            0.0            0.0      0.194000      0.459000   
max    ...            0.0            0.0      0.496000      0.499000   

       sAckDelayMin  rAckDelayMin  sAckDelayAvg  rAckDelayAvg    IT_B_Label  \
count  49844.000000  50804.000000  49844.000000  50804.000000  68729.000000   
mean       0.000101      0.000456      0.011206      0.018510      0.652956   
std        0.000663      0.006664      0.009457      0.022371      0.476033   
min        0.000000      0.000000      0.000132      0.000113      0.000000   
25%        0.000000      0.000000      0.000531      0.000477      0.000000   
50%        0.000000      0.000000      0.015272      0.003247      1.000000   
75%        0.000000      0.000000      0.019493      0.031092      1.000000   
max        0.039000      0.146000      0.109070      0.249889      1.000000   

        NST_B_Label  
count  68729.000000  
mean       0.213898  
std        0.410059  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000  

[8 rows x 55 columns]

## Preprocessing

- Numerical Columns: Columns like sBytesMax, rBytesMax, sBytesMin, etc., have some missing values but not a very high percentage.
- Categorical Columns: Columns like sIPs and rIPs have missing values but again, not a very high percentage.

Given the analysis, we decide to fill in the missing values to avoid losing potentially useful data. For numerical columns, we will use the median, and for categorical columns, we will use the mode.

To train the classification model, we need to transform categorical data into numeric for consistency and to apply algorithms RF and LSTM. We used `LabelEncoder` for this transformation. Additionally, we applied a scaler to preprocess the data, ensuring that numerical features are on a similar scale, which helps improve the performance of LSTM.

In [9]:
numerical_cols = westermo_df.select_dtypes(include=['number']).columns
westermo_df[numerical_cols] = westermo_df[numerical_cols].fillna(westermo_df[numerical_cols].median())

categorical_cols = westermo_df.select_dtypes(include=['object']).columns
print(f"Categorial columns:\n{categorical_cols}")
for col in categorical_cols:
    westermo_df[col] = westermo_df[col].fillna(westermo_df[col].mode()[0])

# print(westermo_df.isnull().sum())

Categorial columns:
Index(['sAddress', 'rAddress', 'sMACs', 'rMACs', 'sIPs', 'rIPs', 'protocol',
       'IT_M_Label', 'NST_M_Label'],
      dtype='object')


In [10]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
category_mappings = {}

for col in categorical_cols:
    le = LabelEncoder()
    westermo_df[col] = le.fit_transform(westermo_df[col])
    label_encoders[col] = le
    category_mappings[col] = {str(original): int(encoded) for original, encoded in zip(le.classes_, le.transform(le.classes_))}

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
westermo_df[numerical_cols] = scaler.fit_transform(westermo_df[numerical_cols])

In [19]:
!pip install imbalanced-learn


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
from imblearn.over_sampling import SMOTE # type: ignore
from imblearn.combine import SMOTETomek

# Handling Class Imbalance
X = westermo_df.drop(['IT_M_Label', 'IT_B_Label', 'NST_M_Label', 'NST_B_Label'], axis=1)
y = westermo_df['IT_M_Label']

smote = SMOTE()
X_res, y_res = smote.fit_resample(X, y)

# smote_tomek = SMOTETomek(random_state=42)
# X_res, y_res = smote_tomek.fit_resample(X, y)

## Feature Selection

Using RF classifier from `scikit-learn`

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42)
rf_classifier = RandomForestClassifier(
    n_estimators=100, 
    random_state=42, 
    n_jobs=-1, 
    class_weight='balanced'
)
rf_classifier.fit(X_train, y_train)
y_pred = rf_classifier.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import cross_val_score

conf_matrix = confusion_matrix(y_test, y_pred)
acc_score = accuracy_score(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
cv_scores = cross_val_score(rf_classifier, X_train, y_train, cv=5)

print("Confusion Matrix:\n", conf_matrix)
print("Accuracy Score:", acc_score)
print("Classification Report:\n", class_report)
print("Cross-validation Scores:", cv_scores)

Confusion Matrix:
 [[4291   72   66   41   22  106   33  146]
 [  57 4353   56   30   22  103   36  151]
 [  76   39 4358   28   37   58   33  130]
 [  55   31   46 4425   24   69   20  108]
 [  21   21   34   22 4520   16   19   54]
 [  46   42   36   35    4 4595   51   31]
 [  87   44   73   42   32   83 4146  203]
 [ 146  110  111   76   34   46  121 4141]]
Accuracy Score: 0.912613981762918
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.90      0.90      4777
           1       0.92      0.91      0.91      4808
           2       0.91      0.92      0.91      4759
           3       0.94      0.93      0.93      4778
           4       0.96      0.96      0.96      4707
           5       0.91      0.95      0.93      4840
           6       0.93      0.88      0.90      4710
           7       0.83      0.87      0.85      4785

    accuracy                           0.91     38164
   macro avg       0.91      0.91   

In [23]:
import numpy as np

# Feature Importance
feature_importances = rf_classifier.feature_importances_
features = X.columns
indices = np.argsort(feature_importances)[::-1]

In [24]:
import matplotlib.pyplot as plt

# Plot Feature Importance
plt.figure(figsize=(10, 6))
plt.title("Feature Importance")
plt.bar(range(X.shape[1]), feature_importances[indices], align="center")
plt.xticks(range(X.shape[1]), features[indices], rotation=90)
plt.show()

In [25]:
# Feature Selection
top_features = features[indices][:10]  # Top 10
print(top_features)
X_train_selected = X_train[top_features]
X_test_selected = X_test[top_features]

Index(['end', 'start', 'startDate', 'endOffset', 'endDate', 'startOffset',
       'sInterPacketAvg', 'duration', 'sLoad', 'rAckDelayAvg'],
      dtype='object')


### RF classifier from `cuml`

In [ ]:
from sklearn.model_selection import train_test_split
from cuml.ensemble import RandomForestClassifier as cuRF
import numpy as np

# Ensure data is in float32 format for pickling
X_train_selected = X_train_selected.astype(np.float32)
y_res = y_res.astype(np.float32)

rf_cuml = cuRF(n_estimators=100, max_depth=20, random_state=42, n_streams=1)    # n_streams=1 for n_streams=1 for reproducibility
rf_cuml.fit(X_train_selected, y_train)
y_pred_cuml = rf_cuml.predict(X_test_selected)